---
operating_system:
- - ubuntu
  - debian
- - '12.04'
  - 12.04.5
  - lts
  - precise
  - pangolin
  - default
osdeps_mode: os,gem,pip
reused_autoproj_installations: []
ruby_executable: /usr/bin/ruby1.9.1
manifest_source:
  type: svn
  url: http://intranet.robotics.esa.int/svn/ROBS/trunk/buildconf
  branch: master
GITORIOUS: git
GITORIOUS_ROOT: git://gitorious.org
GITORIOUS_PUSH_ROOT: ! 'git@gitorious.org:'
SPACEGIT: git
SPACEGIT_ROOT: git://spacegit.dfki.uni-bremen.de
SPACEGIT_PUSH_ROOT: ! 'git@spacegit.dfki.uni-bremen.de:'
GITHUB: http
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: https://github.com
ROCK_FLAVOR: rock1408
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
autoproj_use_prerelease: false
